/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as RetornoRouteImport } from './routes/retorno'
import { Route as PreviaRouteImport } from './routes/previa'
import { Route as PreparandoRouteImport } from './routes/preparando'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomenagemSlugRouteImport } from './routes/homenagem.$slug'
import { Route as ApiPublicDeezerSearchRouteImport } from './routes/api/public/deezer-search'
import { Route as ApiPublicCreateMercadoPagoPreferenceRouteImport } from './routes/api/public/create-mercado-pago-preference'
import { Route as ApiPublicWebhooksMercadoPagoRouteImport } from './routes/api/public/webhooks/mercado-pago'
import { Route as ApiPublicWebhooksCaktoRouteImport } from './routes/api/public/webhooks/cakto'
import { Route as ApiPublicHeroSelectRegenSlugRouteImport } from './routes/api/public/hero-select-regen.$slug'
import { Route as ApiPublicHeroRegenSlugRouteImport } from './routes/api/public/hero-regen.$slug'
import { Route as ApiPublicDeezerTrackIdRouteImport } from './routes/api/public/deezer-track.$id'
import { Route as ApiPublicAudioPreviewIdRouteImport } from './routes/api/public/audio-preview.$id'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RetornoRoute = RetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviaRoute = PreviaRouteImport.update({
  id: '/previa',
  path: '/previa',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparandoRoute = PreparandoRouteImport.update({
  id: '/preparando',
  path: '/preparando',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomenagemSlugRoute = HomenagemSlugRouteImport.update({
  id: '/homenagem/$slug',
  path: '/homenagem/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeezerSearchRoute = ApiPublicDeezerSearchRouteImport.update({
  id: '/api/public/deezer-search',
  path: '/api/public/deezer-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateMercadoPagoPreferenceRoute =
  ApiPublicCreateMercadoPagoPreferenceRouteImport.update({
    id: '/api/public/create-mercado-pago-preference',
    path: '/api/public/create-mercado-pago-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadoPagoRoute =
  ApiPublicWebhooksMercadoPagoRouteImport.update({
    id: '/api/public/webhooks/mercado-pago',
    path: '/api/public/webhooks/mercado-pago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCaktoRoute = ApiPublicWebhooksCaktoRouteImport.update({
  id: '/api/public/webhooks/cakto',
  path: '/api/public/webhooks/cakto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeroSelectRegenSlugRoute =
  ApiPublicHeroSelectRegenSlugRouteImport.update({
    id: '/api/public/hero-select-regen/$slug',
    path: '/api/public/hero-select-regen/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeroRegenSlugRoute = ApiPublicHeroRegenSlugRouteImport.update({
  id: '/api/public/hero-regen/$slug',
  path: '/api/public/hero-regen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeezerTrackIdRoute = ApiPublicDeezerTrackIdRouteImport.update({
  id: '/api/public/deezer-track/$id',
  path: '/api/public/deezer-track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAudioPreviewIdRoute = ApiPublicAudioPreviewIdRouteImport.update({
  id: '/api/public/audio-preview/$id',
  path: '/api/public/audio-preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/preparando': typeof PreparandoRoute
  '/previa': typeof PreviaRoute
  '/retorno': typeof RetornoRoute
  '/sucesso': typeof SucessoRoute
  '/homenagem/$slug': typeof HomenagemSlugRoute
  '/api/public/create-mercado-pago-preference': typeof ApiPublicCreateMercadoPagoPreferenceRoute
  '/api/public/deezer-search': typeof ApiPublicDeezerSearchRoute
  '/api/public/audio-preview/$id': typeof ApiPublicAudioPreviewIdRoute
  '/api/public/deezer-track/$id': typeof ApiPublicDeezerTrackIdRoute
  '/api/public/hero-regen/$slug': typeof ApiPublicHeroRegenSlugRoute
  '/api/public/hero-select-regen/$slug': typeof ApiPublicHeroSelectRegenSlugRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/preparando': typeof PreparandoRoute
  '/previa': typeof PreviaRoute
  '/retorno': typeof RetornoRoute
  '/sucesso': typeof SucessoRoute
  '/homenagem/$slug': typeof HomenagemSlugRoute
  '/api/public/create-mercado-pago-preference': typeof ApiPublicCreateMercadoPagoPreferenceRoute
  '/api/public/deezer-search': typeof ApiPublicDeezerSearchRoute
  '/api/public/audio-preview/$id': typeof ApiPublicAudioPreviewIdRoute
  '/api/public/deezer-track/$id': typeof ApiPublicDeezerTrackIdRoute
  '/api/public/hero-regen/$slug': typeof ApiPublicHeroRegenSlugRoute
  '/api/public/hero-select-regen/$slug': typeof ApiPublicHeroSelectRegenSlugRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/preparando': typeof PreparandoRoute
  '/previa': typeof PreviaRoute
  '/retorno': typeof RetornoRoute
  '/sucesso': typeof SucessoRoute
  '/homenagem/$slug': typeof HomenagemSlugRoute
  '/api/public/create-mercado-pago-preference': typeof ApiPublicCreateMercadoPagoPreferenceRoute
  '/api/public/deezer-search': typeof ApiPublicDeezerSearchRoute
  '/api/public/audio-preview/$id': typeof ApiPublicAudioPreviewIdRoute
  '/api/public/deezer-track/$id': typeof ApiPublicDeezerTrackIdRoute
  '/api/public/hero-regen/$slug': typeof ApiPublicHeroRegenSlugRoute
  '/api/public/hero-select-regen/$slug': typeof ApiPublicHeroSelectRegenSlugRoute
  '/api/public/webhooks/cakto': typeof ApiPublicWebhooksCaktoRoute
  '/api/public/webhooks/mercado-pago': typeof ApiPublicWebhooksMercadoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/preparando'
    | '/previa'
    | '/retorno'
    | '/sucesso'
    | '/homenagem/$slug'
    | '/api/public/create-mercado-pago-preference'
    | '/api/public/deezer-search'
    | '/api/public/audio-preview/$id'
    | '/api/public/deezer-track/$id'
    | '/api/public/hero-regen/$slug'
    | '/api/public/hero-select-regen/$slug'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/mercado-pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar'
    | '/preparando'
    | '/previa'
    | '/retorno'
    | '/sucesso'
    | '/homenagem/$slug'
    | '/api/public/create-mercado-pago-preference'
    | '/api/public/deezer-search'
    | '/api/public/audio-preview/$id'
    | '/api/public/deezer-track/$id'
    | '/api/public/hero-regen/$slug'
    | '/api/public/hero-select-regen/$slug'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/mercado-pago'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/preparando'
    | '/previa'
    | '/retorno'
    | '/sucesso'
    | '/homenagem/$slug'
    | '/api/public/create-mercado-pago-preference'
    | '/api/public/deezer-search'
    | '/api/public/audio-preview/$id'
    | '/api/public/deezer-track/$id'
    | '/api/public/hero-regen/$slug'
    | '/api/public/hero-select-regen/$slug'
    | '/api/public/webhooks/cakto'
    | '/api/public/webhooks/mercado-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  PreparandoRoute: typeof PreparandoRoute
  PreviaRoute: typeof PreviaRoute
  RetornoRoute: typeof RetornoRoute
  SucessoRoute: typeof SucessoRoute
  HomenagemSlugRoute: typeof HomenagemSlugRoute
  ApiPublicCreateMercadoPagoPreferenceRoute: typeof ApiPublicCreateMercadoPagoPreferenceRoute
  ApiPublicDeezerSearchRoute: typeof ApiPublicDeezerSearchRoute
  ApiPublicAudioPreviewIdRoute: typeof ApiPublicAudioPreviewIdRoute
  ApiPublicDeezerTrackIdRoute: typeof ApiPublicDeezerTrackIdRoute
  ApiPublicHeroRegenSlugRoute: typeof ApiPublicHeroRegenSlugRoute
  ApiPublicHeroSelectRegenSlugRoute: typeof ApiPublicHeroSelectRegenSlugRoute
  ApiPublicWebhooksCaktoRoute: typeof ApiPublicWebhooksCaktoRoute
  ApiPublicWebhooksMercadoPagoRoute: typeof ApiPublicWebhooksMercadoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retorno': {
      id: '/retorno'
      path: '/retorno'
      fullPath: '/retorno'
      preLoaderRoute: typeof RetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previa': {
      id: '/previa'
      path: '/previa'
      fullPath: '/previa'
      preLoaderRoute: typeof PreviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparando': {
      id: '/preparando'
      path: '/preparando'
      fullPath: '/preparando'
      preLoaderRoute: typeof PreparandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homenagem/$slug': {
      id: '/homenagem/$slug'
      path: '/homenagem/$slug'
      fullPath: '/homenagem/$slug'
      preLoaderRoute: typeof HomenagemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deezer-search': {
      id: '/api/public/deezer-search'
      path: '/api/public/deezer-search'
      fullPath: '/api/public/deezer-search'
      preLoaderRoute: typeof ApiPublicDeezerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-mercado-pago-preference': {
      id: '/api/public/create-mercado-pago-preference'
      path: '/api/public/create-mercado-pago-preference'
      fullPath: '/api/public/create-mercado-pago-preference'
      preLoaderRoute: typeof ApiPublicCreateMercadoPagoPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercado-pago': {
      id: '/api/public/webhooks/mercado-pago'
      path: '/api/public/webhooks/mercado-pago'
      fullPath: '/api/public/webhooks/mercado-pago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cakto': {
      id: '/api/public/webhooks/cakto'
      path: '/api/public/webhooks/cakto'
      fullPath: '/api/public/webhooks/cakto'
      preLoaderRoute: typeof ApiPublicWebhooksCaktoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hero-select-regen/$slug': {
      id: '/api/public/hero-select-regen/$slug'
      path: '/api/public/hero-select-regen/$slug'
      fullPath: '/api/public/hero-select-regen/$slug'
      preLoaderRoute: typeof ApiPublicHeroSelectRegenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hero-regen/$slug': {
      id: '/api/public/hero-regen/$slug'
      path: '/api/public/hero-regen/$slug'
      fullPath: '/api/public/hero-regen/$slug'
      preLoaderRoute: typeof ApiPublicHeroRegenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deezer-track/$id': {
      id: '/api/public/deezer-track/$id'
      path: '/api/public/deezer-track/$id'
      fullPath: '/api/public/deezer-track/$id'
      preLoaderRoute: typeof ApiPublicDeezerTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audio-preview/$id': {
      id: '/api/public/audio-preview/$id'
      path: '/api/public/audio-preview/$id'
      fullPath: '/api/public/audio-preview/$id'
      preLoaderRoute: typeof ApiPublicAudioPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  PreparandoRoute: PreparandoRoute,
  PreviaRoute: PreviaRoute,
  RetornoRoute: RetornoRoute,
  SucessoRoute: SucessoRoute,
  HomenagemSlugRoute: HomenagemSlugRoute,
  ApiPublicCreateMercadoPagoPreferenceRoute:
    ApiPublicCreateMercadoPagoPreferenceRoute,
  ApiPublicDeezerSearchRoute: ApiPublicDeezerSearchRoute,
  ApiPublicAudioPreviewIdRoute: ApiPublicAudioPreviewIdRoute,
  ApiPublicDeezerTrackIdRoute: ApiPublicDeezerTrackIdRoute,
  ApiPublicHeroRegenSlugRoute: ApiPublicHeroRegenSlugRoute,
  ApiPublicHeroSelectRegenSlugRoute: ApiPublicHeroSelectRegenSlugRoute,
  ApiPublicWebhooksCaktoRoute: ApiPublicWebhooksCaktoRoute,
  ApiPublicWebhooksMercadoPagoRoute: ApiPublicWebhooksMercadoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
